### ISSUE TITLE
Binding to 127.0.1.1 by default.

### ISSUE THREAD

**Issue by ahiscox** [LogicReinc/LogicReinc.BlendFarm#1]
https://github.com/LogicReinc/LogicReinc.BlendFarm/blob/9e1fa91d0d3d3dd376652a08e4fb886faaae3ee1/LogicReinc.BlendFarm.Server/Program.cs#L22

By default on my system (Ubuntu 20.04 LTS) the Server portion is binding to 127.0.1.1
I couldn't find a way to change that, but according to [this post on stackoverflow](https://stackoverflow.com/questions/55296584/getting-127-0-1-1-instead-of-192-168-1-ip-ubuntu-python) it was being caused by a mapping of my hostname to 127.0.1.1 in my /etc/hosts file. I commented out this line and the server started up.

**Comment by LogicReinc** [comment]
Thanks for the note. 
Could you tell me if it was preventing functionality? Or simply the address it was reporting?
The server should not be listening to any specific address, but any address for a specific port (as can be seen in LogicReinc.BlendFarm.Server.RenderServer).
The line you refer to in code is only used to print out the most likely relevant address of the pc it runs on.

So I would assume you could still connect to your machine if you knew the IP address. 
(In which case I will simply list more possible addresses, which will include the relevant one). 
If you have any additional information that would be great.

**Comment by ahiscox** [comment]
I might have jumped the gun, I did have a problem connecting which caused me to research that in the first place, however when I just reset it back to normal I was able to connect just fine (although it does list 127.0.1.1). Perhaps I was having a temporary network issue. Interesting side note; I have a barebones custom ubuntu live usb that I boot for rendering based on Lubuntu, that has the mapping in /etc/hosts but displays the correct address. I'm using the windows client at the moment because I had difficulties with the linux version (select file button did nothing, had to manually enter path, plus random freeze ups), but when I reboot back I will test just to make sure it's not a platform issue.

**Comment by LogicReinc** [comment]
I am able to reproduce the Linux file dialog not working. I forgot to fix this before version 1.0. This is an bug in the UI framework used, and is platform specific to Linux. I'll be fixing this likely this week. Worst case I have to make a custom file dialog.

As my main driver is Windows (using GUI), and some Linux servers, the Windows GUI is most stable as this is what I used for several weeks already. Technically this should translate to similar results in Mac and Linux, as most code is shared, but that assumes no bugs in Avalonia UI.

The "Freezes" you mention are more worrying. If you could reproduce them I'd love to hear how and when. Besides the file dialog I don't remember any other issues with Linux. Hopefully I can get the Linux version semi-production ready this week, as that was the intention.

If you encounter any new issues, please create a separate issue, Thanks.

**Comment by LogicReinc** [comment]
As the FileDialog is a known issue, and will be fixed next release this week or perhaps early next week, ill close this issue. 
If the freezing reoccurs please create a new issue giving some details on this in particular.

**Comment by LogicReinc** [comment]
All solutions mentioned are implemented in Release v1.0.1-alpha
