### ISSUE TITLE
Opening a second server instance on the same computer, for GPU of different vendor

### ISSUE THREAD

**Issue by Charmandrigo** [LogicReinc/LogicReinc.BlendFarm#101]
I have a rig that has two cards connected for computing, a Nvidia one and a AMD one, both support Cuda and HIP respectively but I can only run one server at a time, it says address is in use when opening a second console.

Is there a way to run a second server instance in the same computer, like on a different port? I want to know how to switch it, would be really useful have the two servers running on this same computer for rendering

**Comment by LogicReinc** [comment]
You can modify the settings file and change the port to any other port you like. This should allow you to run 2 servers.
There should be a ServerSettings file in your server directory after booting I believe.
This is a json file. Changing the "Port" property would use a different port (by default 15000)
If it doesn't exist by default, you can create it yourself. Create a file (without extension) called "ServerSettings" in the same directory as the executable.
Then put the following text in it:
```json
{
   "Port": 15001
}
```

**Comment by Charmandrigo** [comment]
> You can modify the settings file and change the port to any other port you like. This should allow you to run 2 servers. There should be a ServerSettings file in your server directory after booting I believe. This is a json file. Changing the "Port" property would use a different port (by default 15000) If it doesn't exist by default, you can create it yourself. Create a file (without extension) called "ServerSettings" in the same directory as the executable. Then put the following text in it:
> 
> ```json
> {
>    "Port": 15001
> }
> ```
only a "versioncache" file is created when running the server
<img width="782" alt="imagen" src="https://github.com/LogicReinc/LogicReinc.BlendFarm/assets/30424766/67e78780-482d-4a39-a020-352607bc620e">
I attempted to create the json file manually tho it still listens to port 15000
<img width="797" alt="imagen" src="https://github.com/LogicReinc/LogicReinc.BlendFarm/assets/30424766/63012b4d-0d70-4506-81eb-fcee88898e79">

**Comment by LogicReinc** [comment]
You have to remove the ".json" extension. The filename should simply be "ServerSettings" without any extension.

**Comment by Charmandrigo** [comment]
<img width="754" alt="imagen" src="https://github.com/LogicReinc/LogicReinc.BlendFarm/assets/30424766/48582a4d-6deb-4820-8c28-9225cadc234e">
Did not worked either

**Comment by Charmandrigo** [comment]
Can you check again with the latest release? Because this hasn't worked of all I have tested

**Comment by LogicReinc** [comment]
@Charmandrigo Sorry for late reply. I tested changing port and it all appears to work fine.
Tested on both Linux and Windows.
Since you're on Linux, did you check file permissions?
Here is the most basic example of it working:
![image](https://github.com/LogicReinc/LogicReinc.BlendFarm/assets/9057113/7c29435a-6d49-40b4-a1cb-ca9d73a91de4)
