### ISSUE TITLE
GPU Rendering

### ISSUE THREAD

**Issue by tomitrescak** [LogicReinc/LogicReinc.BlendFarm#110]
Thanks you for the amazing software! I was wondering how can I convince the software to render on GPU on MAC. I can see that renders are much slower, it seems that GPU is possibly used on Windows not sure. Is there ay flag that I should switch? Rendering in Blender is much faster.

**Comment by pokeslog** [comment]
I don't think he's developing this anymore.

**Comment by LogicReinc** [comment]
@pokeslog I'm, just infrequently due to work.

@tomitrescak CUDA is using both CPU and GPU (Nvidia) to render. CUDA_GPU_ONLY, as the name suggest, only uses your GPU.
