### ISSUE TITLE
Can't use PNG 16b or EXR, jus PNG 8b

### ISSUE THREAD

**Issue by FidoDidoVN** [LogicReinc/LogicReinc.BlendFarm#13]
When I set output is PNG16b or EXR, they said "Image format is unknown". Run well with PNG 8b

**Comment by FidoDidoVN** [comment]
Currently, I use composition with FileOuput node to save my image to another format! Just set the Output in Output Properties is PNG 8bit! Thanks for your work! Amazing app!

**Comment by micpiotrowski** [comment]
Yeah, I agree - **amazing app**!
According to issue #30 - if it would be relatively simple to add a support for other formats (esp. EXR) **for animations** it will be very appreciated!
I thing in general (if it's not a problem) that BlendFarm could just use the output format settings from the .blend file for animations.

**Comment by LogicReinc** [comment]
I've decided to make this a priority for the next release. It requires some rewriting of some systems, but I hope to at least support EXR in next release (next month).

**Comment by Lynchon83** [comment]
Hi, I do managed to render animations in exr format but none of the selected passes in the blend file are saved in the exr files. This announced priority change on exr does it mean passes will be supported?

thanks for this app, I'm using it in production and is just a pleasure.

**Comment by LogicReinc** [comment]
@Lynchon83 Whatever you select in the Blendfarm is generally ignored when it comes to file formats (the script sets it to PNG for support). The files are sent to back through BlendFarm and are converted as PNG files. (I might have to double check).
I assume once I remove the limitation of PNG that your passes will work (For animation), as at that point I will try to avoid changing any of the files from Blender and provide them as is.

**Comment by ichswarox** [comment]
EXR

> I've decided to make this a priority for the next release. It requires some rewriting of some systems, but I hope to at least support EXR in next release (next month).

EXR and multilayer is important feature, thanks!

**Comment by ichswarox** [comment]
EXR

> I've decided to make this a priority for the next release. It requires some rewriting of some systems, but I hope to at least support EXR in next release (next month).

EXR and multilayer is important feature, thanks

**Comment by LogicReinc** [comment]
@FidoDidoVN @micpiotrowski @Lynchon83  @ichswarox 
Version 1.1.2 brings support for all Blender file formats for animations 
(resulting images are not altered by BlendFarm, thus should support any special settings you have in Blender for said type as well)

Enjoy
