### ISSUE TITLE
Connection / remote job problem

### ISSUE THREAD

**Issue by wschildbach** [LogicReinc/LogicReinc.BlendFarm#16]
I am having trouble getting a job to render remotely. Here is my setup.

I have host A (192.168.0.43) and host B (192.168.0.64). Both are Windows 10 systems; A is a laptop while B is a desktop with a graphics card. I am running the BlendFarm UI on both systems.

I can render a simple test file fine on either system locally. However, when I start the job on A, to render on B, the UI on A tells me
> [3/3] cannot access a disposed Object name: 'System.NetSockets.TcpClient'.

A's console says:
> Saving current setting states
> Showing OpenFileDialogShowFileDialog Results: Received computerInfoResp [81] from [::ffff:192.168.0.43]:15000
> Received prepareResp [44] from [::ffff:192.168.0.43]:15000
> Received syncResp [86] from [::ffff:192.168.0.43]:15000
> Received syncUploadResp [44] from [::ffff:192.168.0.43]:15000
> Received syncCompleteResp [44] from [::ffff:192.168.0.43]:15000
> Received checkSyncResp [44] from [::ffff:192.168.0.43]:15000
> Received checkSyncResp [44] from [::ffff:192.168.0.43]:15000
> Received isBusyResp [43] from [::ffff:192.168.0.43]:15000
> TCP listening exception: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host..

B's console says:
> Received renderResp [483472] from [::ffff:127.0.0.1]:15000
> Received computerInfo [42] from 192.168.0.64:56734
> Received prepare [61] from 192.168.0.64:56734
> blender-2.92.0 already present
> Received sync [95] from 192.168.0.64:56734
> Received syncUpload [2654296] from 192.168.0.64:56734
> Received syncComplete [83] from 192.168.0.64:56734
> Received checkSync [91] from 192.168.0.64:56734
> Received checkSync [91] from 192.168.0.64:56734
> Received isBusy [42] from 192.168.0.64:56734
> Received render [291] from 192.168.0.64:56734
> TCP listening exception: Failed to parse RenderRequest due to:Decimal byte array constructor requires an array of length four containing valid decimal bytes."

Vice versa, starting the job on B, to render on A, the UI on B says
> Outdated  protocol, update node before connecting (Protocol:2, found: )

and A's console says:
> Received checkProtocol [58] from 192.168.0.43:50464
> Received ☺       ♣   ☻   ☺$   4b9 [1714631475] from 192.168.0.43:50464
> Received b-0909-46d0-88c4-035afd5 [945960291] from 192.168.0.43:50464
> TCP listening exception: Expected header of length 24, found 2

Any hunch as to what is going on or what other tests I could be conducting?

Thanks for this project, it looks like it could be super useful!

**Comment by LogicReinc** [comment]
Seems the connection is getting closed by the other computer (or by network). Ensure firewall isn't blocking it somehow. Or perhaps unstable. I do vaguely remember that there is some networking code that needs improving in case of an unstable connection. I may look at it tomorrow. For now I recommend you making sure you use an ethernet cable.

**Comment by wschildbach** [comment]
Thanks for the hints.

I have now also set up a machine C, a linux server. The problems are the same.

All three machines are using wired ethernet. I have set up some VLANs here, might this be part of the problem?

**Comment by wschildbach** [comment]
I now tested starting the job on B and rendering on C, this works fine. The problem seems to be with machine A which I don't administer, and don't entirely know what its network stack is. So as far as that goes, you can consider the problem closed (or "won't fix").

If it helps tp improve robustness though, I am happy to help with further debugging.

**Comment by wschildbach** [comment]
One final (?) comment, I just noticed that simply opening the UI on machine A, and closing the UI, throws an error in the console right before it is closed:
> TCPError: cannot access a disposed object.
> Object name: 'System.NetSockets.TcpClient'.

**Comment by LogicReinc** [comment]
Good to hear it was not directly related to the software networking.
Closing the UI (exiting) is supposed to close the application itself.
It is likely cleaning up and disposing the sockets while it was still reading from said socket.
This can be ignored for now.
