### ISSUE TITLE
Hope there is an auto reconnect feature.

### ISSUE THREAD

**Issue by megabitsenmzq** [LogicReinc/LogicReinc.BlendFarm#18]
The network condition of my nodes is not very well. If there is an auto-reconnect feature it will be very useful.

**Comment by LogicReinc** [comment]
Reconnecting isn't too hard to add. Resuming work on nodes that got disconnected midway is a bit more work (So work starts on 2 nodes. Node 2 drops out, and its work is left undone). I assume your intention is the latter?

**Comment by megabitsenmzq** [comment]
Yes, I want to resume the work. Maybe you can save a list of all the failed frames, and render them after all frames in the queue are done.

**Comment by LogicReinc** [comment]
Certainly, There are plenty of ways to implement it. But has to be integrated into the existing flow. You also get the downside that distribution gets messed up. So it might even be worth redistributing the remainder again over all machines after reconnection.

But I'll think about it. Hopefully I can do it this month (Im quite occupied at the moment, so I can't make promises.)

**Comment by megabitsenmzq** [comment]
I’ll wait for that. This tool is really easy to use. Thank you for your hard work. 😁

**Comment by LogicReinc** [comment]
@megabitsenmzq V1.1.3 has basic reconnection build in. Meaning that during a render it will attempt to reconnect a certain number of time within a certain timespan. While you do not want it to disconnect often, it may help.
