### ISSUE TITLE
Cannot use CUDA with Blender 3.0, Windows?

### ISSUE THREAD

**Issue by jpvivere** [LogicReinc/LogicReinc.BlendFarm#21]
Thank you for this program. 

I occasionally use Blender and have just updated my PC workstation and one network PC to version 1.0.8. After some testing, I've discovered that I can no longer render with my Nvidia PCs set to CUDA in BlendFarm using a Blender 3.0 file. (CPU rendering still works). This occurs if I attempt to render either on the local PC only, or the network PC only.

Some cursory debugging has revealed (in my case) that the `cyclesPref.get_devices()` call in render.py returns "None", and thus the render attempt crashes [here ](https://github.com/LogicReinc/LogicReinc.BlendFarm/blob/a7191e0308710d074b4ce53c73c6526693f4d8ff/LogicReinc.BlendFarm.Server/render.py#L34) with the exception "cannot unpack non-iterable NoneType object."

That's as far as I got in trying to debug. I know they're always modifying the Python API over there. 

Hope it's an easy fix! Thanks!

**Comment by LogicReinc** [comment]
Hey @jpvivere ,

Sounds like an easy fix. Ill take a look and fix it this week.

**Comment by LogicReinc** [comment]
@jpvivere Fixed in 1.0.8.1.
Blender decided to remove the function, then add it back in but return nothing.
But resolved it by changing the calls for >= 3.0.

Enjoy.
