### ISSUE TITLE
can't run the client

### ISSUE THREAD

**Issue by dezpan** [LogicReinc/LogicReinc.BlendFarm#3]
![image](https://user-images.githubusercontent.com/74313587/116642138-bf0b9180-a9a0-11eb-9661-47ea8ab7abed.png)
I stuck at this page, then the program is lost response,and force closed.

is the client need some prerequisite to run?

**Comment by dezpan** [comment]
![image](https://user-images.githubusercontent.com/74313587/116726177-83f77580-aa15-11eb-85ae-329a68594286.png)

the error looks like this, see picture above, so I followed the keywords " Unable to read data from the transport connection : An existing connection was forcibly closed by the remote host " to this article https://stackoverflow.com/questions/5420656/unable-to-read-data-from-the-transport-connection-an-existing-connection-was-f

someone suggest to upgrade the .net runtime, I gave a try, and it works.

I countered the problem when I try to run blendfarm the first ,so it’s not related to the number of computers. i still got some PC have the same problem and not upgrade the .net 4.8, if you need, i can record videos.

**Comment by LogicReinc** [comment]
The stackoverflow link is more general.
Could you try to visit this url: https://download.blender.org/release/
If you can visit that url, then I know for certain that the issue is elsewhere.

Since its an SSL exception, make sure your system time is up2date.

**Comment by LogicReinc** [comment]
I think I misread your post. You said you fixed it by upgrading to .net 4.8?
So does installing .net 4.8 solve this issue?
Your PCs seem to be running Windows 7, so it might be related to outdated libraries, and installing 4.8 solves this.

**Comment by dezpan** [comment]
> The stackoverflow link is more general.
> Could you try to visit this url: https://download.blender.org/release/
> If you can visit that url, then I know for certain that the issue is elsewhere.
> 
> Since its an SSL exception, make sure your system time is up2date.

I tried your suggestion, and the problem disappear, it can successful load the UI, 
the problem machine was offline,when I connected to the internet the problem gone.

 that PC "solved" by .net 4.8, I'm not sure now, because I connected the machine to internet to search and download. now i think it's also the SSL problem.

**Comment by LogicReinc** [comment]
No problem, just happy it wasn't a big issue.
At this moment it requires internet to fetch Blender versions (shown in UI) and to download Blender when installation is missing.
I can add a fallback that if it cannot fetch new versions, but a cache exists (VersionCache file) it will return that.
It will still need internet access to download blender versions if they are not present.

I can probably modify it so that it will function when offline in the future (but it will require more setup on your part).

**Comment by dezpan** [comment]
ok,thanks for your great job.

**Comment by LogicReinc** [comment]
@dezpan I double checked the source code, and after fetching versions for the first time, and making sure you download the version of Blender you need (by connecting to it once). BlendFarm should be able to function without internet connection.
Hopefully this helps.
