### ISSUE TITLE
Not work in eevee mode

### ISSUE THREAD

**Issue by ichswarox** [LogicReinc/LogicReinc.BlendFarm#35]
Have anyone try to render in eevee mode?

**Comment by LogicReinc** [comment]
If it didn't work at all it wouldn't be in the application.

I suspect you are trying to use Eevee using a headless linux render node.
Eevee does not support headless Linux machines. This is a Blender limitation as Eevee works fundamentally different.
On Windows this runs fine.

**Comment by ichswarox** [comment]
> If it didn't work at all it wouldn't be in the application.
> 
> I suspect you are trying to use Eevee using a headless Linux render node. Eevee does not support headless Linux machines. This is a Blender limitation as Eevee works fundamentally different. On Windows this runs fine.

Thanks for your quick reply, great addon, I will do another test tomorrow, my computer is a MacBook, render node is a windows pc with 2070 and I use Microsoft remote desktop, so it's not a headless render node, I don't exactly remember the error message, maybe it's "CGI xxxxxx", I will give another try tomorrow.

**Comment by ichswarox** [comment]
Also get this error, Eevee mode and remote desktop active, returned the render result then I get the error warning.  https://ibb.co/K6TQ4LS

**Comment by LogicReinc** [comment]
This checks out. As Eevee needs a desktop environment to render. And Windows probably unloads that when you close the connections and it doesn't have any video out. As mentioned before, I cannot fix it as its a fundamental limitation of Eevee and Blender.
The other error is the same issue as https://github.com/LogicReinc/LogicReinc.BlendFarm/issues/32
Which is an error that only happens on MacOS I believe and will not result in any functional issues and can be ignored, its just an annoyance that I will revisit soon.
