### ISSUE TITLE
No usable version of libssl was found

### ISSUE THREAD

**Issue by IntelMiner** [LogicReinc/LogicReinc.BlendFarm#36]
Hi,

I'm a bit of a novice to Blender. But I'm trying to run the latest server app on a Linux x64 host

When I connect to it I see the following output

IP Addresses of this Server:
Host Address #1: 192.168.1.199
Port: 15000
Cleaning up old sessions..
Server Started
Received checkProtocol [58] from 192.168.1.100:1254
Received computerInfo [42] from 192.168.1.100:1254
Received prepare [60] from 192.168.1.100:1254
No usable version of libssl was found
Aborted (core dumped)

It seems to not like the version of OpenSSL I've got, if I understand it correctly? I'm not sure what needs to be done to make it work with OpenSSL 3.0.2

**Comment by LogicReinc** [comment]
At a glance it appears it fails when trying to download new Blender versions which are behind SSL, which makes sense.

What Linux Distro do you use? I personally test it mostly against Debian/Ubuntu as its most common.
I suspect your distro is missing a commonly available OpenSSL version.

Could you try installing OpenSSL 1.1 and see if that works?

**Comment by IntelMiner** [comment]
I use Gentoo which does make things more difficult as it's rolling release. The machine needs OpenSSL 3.0 for Kernel TLS support for Nginx, downgrading unfortunately isn't an option

It may be possible to replicate it with a distro that also packages OpenSSL 3.0 like Debian Unstable. Though I don't know which ones specifically are packaging it outside of Gentoo

**Comment by IntelMiner** [comment]
I use Gentoo Linux x64

It's currently running OpenSSL-3.0.2 as a "[keyworded](https://wiki.gentoo.org/wiki/KEYWORDS)" package

If you'd like I'd be happy to test binaries on my machine or private access to a machine with the same OpenSSL version for testing

**Comment by LogicReinc** [comment]
I might pick you up on your offer, saves me some time on setting up another VM.
Perhaps ill drop a quick deploy with the updated runtime upcoming week in this issue and you can let me know. 
It would also allow you to work with BlendFarm earlier using that build temporarily if it works.

**Comment by IntelMiner** [comment]
No need to rush :) my roommate wanted a faster way to render and asked to "borrow" my server compute for it. I'm not really intimately familiar with how Blender works otherwise, so I'm grateful there's a tool that makes it point-and-click

**Comment by LogicReinc** [comment]
Hey @IntelMiner ,
Sorry for the late reaction, Had a busy week.
Here is the server compiled on .NET 6.0, which I believe has early support for OpenSSL-3.x.
If this does not work I will need to wait till .NET 7.0 for full OpenSSL support.

You can download the build here: 
https://github.com/LogicReinc/LogicReinc.BlendFarm/blob/dev-1.1.2/.data/BlendFarm.Server-1.1.1.1-Linux64.zip

Let me know how it goes, so I can mark this as solved

**Comment by IntelMiner** [comment]
Looks good on my end. I tested both CPU and CUDA rendering modes successfully. Blazing fast!

**Comment by LogicReinc** [comment]
Good to hear, In next release (this week or next week) it will be fixed across all builds.
(Ill keep this issue open till the release)

**Comment by LogicReinc** [comment]
@IntelMiner The runtime upgrade to .NET 6.0 is now applied to version 1.1.2 across all builds. (Thus by your report should fix OpenSSL 3.x)
