### ISSUE TITLE
Failed Version message on another subnet

### ISSUE THREAD

**Issue by scoobdoomt** [LogicReinc/LogicReinc.BlendFarm#39]
Hello,
I have been testing BlendFarm on a few of my computers. When using BlendFarmServer-1.1.1 on the same subnet XXX.XXX.103.255 as the BlendFarm-1.1.1 client, everything works as expected.
When using BlendFarmServer-1.1.1 on another subnet XXX.XXX.104.255, I get the following response on the server:

IP Addresses of this Server:
Host Address #1: XXX.XXX.104.152
Port: 15000
Cleaning up old sessions..
Server Started
Received checkProtocol [58] from XXX.XXX.103.82:53931
Received computerInfo [42] from XXX.XXX.103.82:53931
Received prepare [60] from XXX.XXX.103.82:53931
Failed to load versions due to The operation has timed out.
TryPrepare failed due to: The operation has timed out.

The client warning is the following: "Failed Version blender-3.1.2".
Client and servers (Windows 10 64-bit) all have Blender 3.1.2 already installed. I also tested to copy the Blender folder from a working server to the ones with the issues. Ping from client to server on the other subnet is working, too.
Is there a known limitation for subnets or do you know a way to make it work?
I appreciate your hard work and would like to test this further!

**Comment by LogicReinc** [comment]
From what you described, Im assuming those computers do not have internet access.
BlendFarm actually ignores any existing installations of Blender (your traditional install)
And handles versions of Blender in its own directory. This is to ensure the same version is used across every computer when rendering (and automatically updating to new versions without touching render nodes).
I don't think it has anything to do with the subnets, just your firewall for those computers not being allowed to download the versions from the internet.

If you REALLY want to pre-install Blender, you need to extract it to a very specific directory next to the executable.
BlendFarm has the option on the launcher "Add Custom Version" that walks you through the process.

Alternative (not recommended) you can add your specific version using the normal numbering as well by placing it at the right location. (Namely: BlenderData/blender-x-y-z-windows64, where x,y,z = version numbers, blender.exe should be in that directory)
Note that if your client selects any other version than the pre-installed one it will attempt to download that version, and if you block internet, will give you that response again.

**Comment by LogicReinc** [comment]
If you have any more info, or if this doesn't seem right, let me know.
