### ISSUE TITLE
One of the computers is not rendering some materials

### ISSUE THREAD

**Issue by marcse9** [LogicReinc/LogicReinc.BlendFarm#41]
![01](https://user-images.githubusercontent.com/108395627/176407537-46d3a34d-5505-4c54-960e-94938b269241.png)

The problem arises when I trying render projects saved on main computer using for rendering two computers. The second one does not render some of materials.

**Comment by LogicReinc** [comment]
@marcse9 My guess is that the left part is rendered on your local computer. And that the paths inside your Blenderfile (for the missing materials) are paths on that computer, and thus it works as expected there.
Did you embed all materials? Did you add the couch materials later perhaps and need to re-embed them?
That's my best guess without more info.
Unless you are using the Networked Paths feature, it has likely to do with embedding the resources.

**Comment by LogicReinc** [comment]
@marcse9 For reference, its also covered in the first 10-15 sec of the BlendFarm tutorial:
https://www.youtube.com/watch?v=EXdwD5t53wc
(The link that opens when you press the Help button)
