### ISSUE TITLE
How to build the solution file

### ISSUE THREAD

**Issue by cyanling2** [LogicReinc/LogicReinc.BlendFarm#42]
Hi, I am trying to add some modifications to the source code and build my customized client and server. Could you please release some instructions on how to execute the build (.NET version, visual studio version, configurations, etc)?

**Comment by cyanling2** [comment]
![image](https://user-images.githubusercontent.com/49295126/176746707-6189e23b-ef7b-4d5f-9f9c-7adeaaf9a952.png)

Sorry I am still confused at this point. I am trying to build the client on windows using VS-2022, Yet, it seems that the main method is missing.

**Comment by LogicReinc** [comment]
LogicReinc.BlendFarm does have a Main.
LogicReinc.BlendFarm.Client does not, as it is not an executable, it is a library. For whatever reason it is not configured as such there?
LogicReinc.BlendFarm.Client is also netstandard2.0, not net6.0 (seeing that its a library).

Did you change anything that could cause this?
Showing the settings of LogicReinc.BlendFarm.Client would help (right click that project=>Properties)
It should look as follows:
![image](https://user-images.githubusercontent.com/9057113/176748095-f0a7ee6e-6bcc-4f02-9e98-822242d02bd1.png)

**Comment by cyanling2** [comment]
oh i see. I set the output type of LogicReinc.BlendFarm.Client as windows application and that's why. Don't remember when I made that change but it works now. Thank you!
