### ISSUE TITLE
OpenCL Removed in 3.10, add HIP Support please.

### ISSUE THREAD

**Issue by Kodey-Kayla** [LogicReinc/LogicReinc.BlendFarm#45]

**Comment by LogicReinc** [comment]
I'll see what I can do regarding this this month, if it uses the standard format and doesn't require any odd configurations it should be an easy fix.

**Comment by LogicReinc** [comment]
@Kodey-Kayla HIP, Metal, OneAPI is available in V1.1.3.
I however wasnt able to test it as I do not have the hardware setup at the moment.
If this solves it, please let me know.
