### ISSUE TITLE
No Optix RenderType.

### ISSUE THREAD

**Issue by gadaszewski** [LogicReinc/LogicReinc.BlendFarm#47]
![image](https://user-images.githubusercontent.com/32915902/195431597-ca862fe3-fbb0-4342-b38f-0af25b0dba6e.png)
Can't find Optix option here.

**Comment by LogicReinc** [comment]
You want the GPU to be either CUDA or CUDA_GPUONLY, then under the System tab, you can switch to the Optix engine.

![image](https://user-images.githubusercontent.com/9057113/195433133-8f91169e-d571-4686-9823-db46b6a286a6.png)
