### ISSUE TITLE
Lacks the option to change the framerate of the animation

### ISSUE THREAD

**Issue by alessiojpg** [LogicReinc/LogicReinc.BlendFarm#5]

**Comment by LogicReinc** [comment]
You can specify framerate in Blender, Blendfarm will use those settings.
Is there a specific scenario when/why you want to set it in BlendFarm?

**Comment by LogicReinc** [comment]
I guess because BlendFarm renders each frame independently.
I'll see what I can do for you in upcoming release

**Comment by LogicReinc** [comment]
Implemented in version v1.0.5
Note, FPS does not really affect frames rendered (unless time is an actual aspect say simulations)
I suspect your issue might not be related to the framerate, but that BlendFarm starts at frame 0.

(So rendering 0 to 60 means you're rendering 61 frames, not 60)
Hopefully this helps/explains it.
