### ISSUE TITLE
impossible to use compositing from my blend scene

### ISSUE THREAD

**Issue by kengi17** [LogicReinc/LogicReinc.BlendFarm#50]
I've try few time, but when the render is done he doesnt finish with the compositing pass, where i have my denoiser node and color grading, is it possisble to add that, the software is great, but that option is really important.

thanks

**Comment by LogicReinc** [comment]
I believe compositing is indeed disabled. The reason being that each part is rendered by a completely different machine.
This might cause artifacts if done. However, I'll see if I can add an option to enable it. In case you do want to try it.
I likely will have a new build this week or during Christmas.

**Comment by kengi17** [comment]
That is great cause i use custom denoiser node, where it's better to optix denoiser, and many people use ut as color grade or something, so yes an option would be great, thx.

Also, i dont know if you think improve the UI, but maybe i could help to design it if it's interest you, as i think it's a great software, lot of people and small studio looking for solution like this!

good job btw.

**Comment by LogicReinc** [comment]
The UI does not have a priority at the moment. I could make something better, but this is just a hobby project. I can't spend much time on it. So the time I do spend on it are actual features and bug fixes. The UI code isn't particularly great either as it was partially an experiment with this particular UI framework for cross-platform. So the less I have to touch it the better.

Do note that BlendFarm allows you to select the denoisers that Blender supports (NLM, OPTIX, OpenImageDenoiser). But I assume you mean a third-party plugin denoiser or something.

I was considering making a studio version of it more targeted towards a professional audience adding features like multi-user, machine management, resource allocation, etc.. but my time is very constraint and I wasn't sure there was a market for it (As I don't have much metrics on usage, and not many donations came through). So I left it for what it was.

**Comment by kengi17** [comment]
I user custom node denoiser into compositing, it's but it's not an addon, so if you can just add the compositing option that would be nice, and not expeciatly because of the denoiser but also for other.

i have work in few small 3D studio, and they looking all for some software to manage like 3 or 6 computer, myself i have 3 renderfarm server, so i think with more publicity it can be an great tool.

**Comment by kengi17** [comment]
Apparently we can render with GPU in Optix mode, but i dont see Optix option on the software setting, i only see CUDA, can u let me know how does it work?  thx

**Comment by LogicReinc** [comment]
@kengi17 See #55

**Comment by LogicReinc** [comment]
Solved by putting Denoiser to None, closing this issue.
