### ISSUE TITLE
3.4 blender versions not working

### ISSUE THREAD

**Issue by GDurrens** [LogicReinc/LogicReinc.BlendFarm#51]
Hi Thank you so much for this work.
I notice that any version above 3.4 triggers a message "missing files ?" and the render fails. Changing just the version to below 3.4 works so that's not a permission or file issue.
I'm using linux.
Any idea ?

**Comment by GDurrens** [comment]
Just notices that the server throws in the console :
`error while loading shared libraries: libsycl.so.6: cannot open shared object file: No such file or directory`

**Comment by GDurrens** [comment]
Ok, I just renamed the file "libsycl.so.6.1.**" found in Blender Data corresponding to the version 3.4+ folder by "libsycl.so.6" and it worked...

**Comment by LogicReinc** [comment]
@GDurrens I found that apparantly, starting Blender 3.4, it is using symlinks in their deployment packages. These are not properly handled by my extraction code.
For now I've solved this in the new version by copying the symlinks instead. This may cost a few extra megabytes but atleast it works universally.

**Comment by LogicReinc** [comment]
Fixed in release 1.1.4
