### ISSUE TITLE
different resolution in different scenes

### ISSUE THREAD

**Issue by GDurrens** [LogicReinc/LogicReinc.BlendFarm#54]
Sorry to bomb with issues but I think BlendFarm is worth giving feedback.
When choosing a different scene in blender with different camera output resolution, that doesn't get transfered to BlendFarm in Live Render mode. We need to either manually set the resolution or reload the .blend file, which is annoying..

**Comment by LogicReinc** [comment]
BlendFarm does not actively specify a scene, and should automatically use the "main" scene for rendering. Currently the BlendFarm client (if its not rendering) is not actually aware of what your blendfarm contains, as this would require the Client to also install Blender even if its not rendering. In the future I'd like to add this as an option though.

There might be an option to add a textbox where you can type the name of your scene, and then that is used.. Is this sufficient for your case?

**Comment by LogicReinc** [comment]
Sorry, I might have misread this issue.
At the moment, camera resolution is always ignored and the resolution you put in BlendFarm is always used. This is vaguely related that if I wanted to match the resolution as inside the .blend file, I'd need to parse it first.  This is planned at a later date due to the above reasons.

**Comment by GDurrens** [comment]
> There might be an option to add a textbox where you can type the name of your scene, and then that is used.. Is this sufficient for your case?

Yeah that would do it and I think it would be a great addition to be able to choose the scene rendered !
I wish I could code to help you with this.

**Comment by LogicReinc** [comment]
Change in release 1.1.4

**Comment by GDurrens** [comment]
I cannot get this to work...
I select my scene (Portrait) in blender. the resolution is 1000x1600.
![image](https://user-images.githubusercontent.com/17565020/210354676-7ee2f993-de3c-4475-ade7-7f7bb67ee9b3.png)
![image](https://user-images.githubusercontent.com/17565020/210354992-afcd5529-8206-40d5-95f1-fdb688aed284.png)
![image](https://user-images.githubusercontent.com/17565020/210354769-cc8b84c4-8ad5-45d7-8554-ccf8d58f7429.png)
I enter "Portrait" but it still renders the 1280x720 that is in Blendfarm...

**Comment by LogicReinc** [comment]
Thats correct, as previously mentioned, BlendFarm is not actually aware of the resolutions in your file, at the moment it will always use the resolutions used in BlendFarm.
For that to be supported I'm going to have to implement a inspect method first, so the BlendFarm can read out such data. Which is planned at a later date, as this is a bit more involved.
