### ISSUE TITLE
Optix option not appear

### ISSUE THREAD

**Issue by kengi17** [LogicReinc/LogicReinc.BlendFarm#55]
![Sans titre](https://user-images.githubusercontent.com/397339/209681285-3afbe0f8-fb9d-41b9-87c5-80ac92c2cd3f.jpg)
I've try to find how to enable OPTIX option but look like my render work with CUDA as the render is very very long.

how can i find OPTIX option for my RTX gpu?

Thanks

**Comment by LogicReinc** [comment]
You select CUDA/CUDA_GPUONLY, then under denoiser options you can select OPTIX. This will use the OPTIX renderer/denoiser.
![image](https://user-images.githubusercontent.com/9057113/209700500-e7afb3fc-19b6-4f72-8e3b-ea71a0dd9c3a.png)

**Comment by kengi17** [comment]
Yes but that not what i'm saying, OPTIX option you show me is for the denoising.

By clicking CUDA option like you say, the GPU is running into CUDA mode where RTX gpu using OPTIX running.

CUDA mode get down the speed of all RTX gpu.

What u show me is the equal on the red square in my picture example, but what i looking is the blue square option.

![Sans titre](https://user-images.githubusercontent.com/397339/209700984-550981cf-42e2-495b-8f31-ff94ab933526.jpg)

**Comment by LogicReinc** [comment]
At the moment, selecting the OPTIX denoiser inside BlendFarm should change both rendering tech to OPTIX as well as the denoiser. BlendFarm options do not neccesarily all map one-to-one to Blender.
I can disconnect the two in the next update.

**Comment by kengi17** [comment]
Ah ok, yes it would be better to separate them, cause it's not logic, good to know.

Adding OPTIX in device settings and OPTIX for denoiser is good, ho btw for the denoiser i've test, if i set denoiser to NONE, the compositing work and my custom denoiser working as well. :)

thank

**Comment by LogicReinc** [comment]
Thats good to hear

**Comment by LogicReinc** [comment]
@kengi17 To clarify, my previous explanation was incorrect.
If you change the engine (Under system) to Optix, it will use all CUDA gpus (and cpu if not GPU_ONLY) as OPTIX GPUs.
This allows you to quickly switch between Optix and CUDA without having to change all your machine's configuration.

I still recommend this workflow. But to avoid confusion I'm additionally adding it as an option of a specific machine.

**Comment by LogicReinc** [comment]
Change in Release 1.1.4
