### ISSUE TITLE
Render Failed with notif "Stream was too long"

### ISSUE THREAD

**Issue by fadel78** [LogicReinc/LogicReinc.BlendFarm#62]
I have a render file within 3GB size, when I render it appears a notification "Stream was too long". did blendfarm have a limited size of rendering?

thanks

**Comment by LogicReinc** [comment]
I believe there should be no technical limitation, however I might have added a condition that gives that exception to prevent a run-away package or something.

3GB is also quite big for a blender file to sync.
Ill make sure to up the limit next build. Next build will hopefully also have asset-sync, so you don't have to embed everything.

**Comment by fadel78** [comment]
sry for my miss click, btw is blendfarm have a API in this application?

**Comment by LogicReinc** [comment]
The nodes have a custom binary protocol which is used to communicate with them.
BlendFarm is a server-less system, meaning that the client is in charge of proper operation.
So an API is a bit difficult. Unless you mean an API on the client application, which is technically possible.
But a bit annoying as BlendFarm is in charge of managing states.

**Comment by LogicReinc** [comment]
Solved in upcoming 1.1.5
