### ISSUE TITLE
Color management or something... image doesn't match up

### ISSUE THREAD

**Issue by hurricanz** [LogicReinc/LogicReinc.BlendFarm#64]
using the latest version and Blender 3.4.1.

https://i.imgur.com/jPzdzML.png

I even copied the blender install within the Blenderdata to the other workstation.  it is still off.

both commandlines say the same thing too:  
Color management: display "sRGB" used by scene not found, setting to default ("ACES").
Color management: scene view "Filmic" not found, setting default "sRGB".
Color management: sequencer colorspace "sRGB" not found, will use default instead.

Essentially they should be identical but they are not.  I tried both server and other on the other workstation and it still produces a darker image.

**Comment by hurricanz** [comment]
![jPzdzML](https://user-images.githubusercontent.com/31371270/225031248-8abc242d-65c0-4a65-adc2-2247379908f6.png)

**Comment by hurricanz** [comment]
lastly.. mainly a nitpick:   your versioning is out of order.  
![Screenshot 2023-03-14 102453](https://user-images.githubusercontent.com/31371270/225032022-ae468bf5-f98b-4650-b5c2-01578c593298.png)

**Comment by hurricanz** [comment]
nevermind.. apparently this is an ongoing issue with BlendFarm.  I may just stick with Deadline.

**Comment by LogicReinc** [comment]
Intention is to fix it, but I'm on a business trip at the moment so its very hard to allocate time.
If this is critical for you it is better to stick what worked for you for now.
