### ISSUE TITLE
Feature Request - Way to access the STDOUT from the server within the GUI of the client!

### ISSUE THREAD

**Issue by paperschool** [LogicReinc/LogicReinc.BlendFarm#65]
What it says on the tin! Be nice to see the Server STDOUT somewhere to improve debugging / understand progress!

**Comment by LogicReinc** [comment]
I'll see if I can add a setting to enable forwarding of logs in the next build.  I can't really give an estimate as I'm on a long business trip.

**Comment by LogicReinc** [comment]
Solved in upcoming release (1.1.5)
