### ISSUE TITLE
ZIP file for version 1.1.4 from the releases link contains a v1.0.3 file

### ISSUE THREAD

**Issue by miracuruzrh** [LogicReinc/LogicReinc.BlendFarm#66]
Hello

Just want to give the information, that when I unzip the v1.1.4 release file, that the LogicReinc.BlendFarm.app has stored metadata which says it is v1.0.3. I think it is the correct version as it was created on the release day. I have attached a screenshot where th v1.0.3 is visible.
![Greenshot 2023-03-22 21 50 52](https://user-images.githubusercontent.com/44341190/227035994-88d6ae15-e0ff-430d-8175-faabb34b9826.png)

**Comment by LogicReinc** [comment]
Sorry for the late reaction, Thanks for the information.
It shouldn't change the functionality, but it should indeed be fixed in my build script.
