### ISSUE TITLE
SSL Falled Version blender3 

### ISSUE THREAD

**Issue by kolotovalexander** [LogicReinc/LogicReinc.BlendFarm#68]
У меня проблема с SSL. 
Версия blender-v3.5-release

Создаю сцену в blender на macOS, на macOS открываю BlendFarm-1.1.4-OSX64. На Windows включаю BlendFarm.Server-1.1.4-Win64. В BlendFarm-1.1.4-OSX64 отображается список из двух устройств:
Local localhost: 15000
PC 192.168.1.105:150
При включении PC 192.168.1.105:150 в этом списке появляется ошибка:
Local localhost: 15000
PC 192.168.1.105:150 **Failed Version blender-3**
В командной строке BlendFarm.Server-1.1.4-Win64 отображается следующее:
IP Addresses of this Server:
Host Address #1: 192.168.1.105
Host Address #2: 192.168.1.106
Port: 15000
Cleaning up old sessions..
Server Started
Received checkProtocol [58] from 192.168.1.47:55028
Received computerInfo [42] from 192.168.1.47:55028
Received prepare [60] from 192.168.1.47:55028
**Failed to load versions due to The SSL connection could not be established, see inner exception.
TryPrepare failed due to: The SSL connection could not be established, see inner exception.**

Если на Windows включаю BlendFarm-1.1.4-Win64
Командная строка показывает это:
LogicReinc.BlendFarm v1.1.4.0
Saving current setting states
Fetching versions from cache or remote
Failed to load versions due to The SSL connection could not be established, see inner exception.
Fetching announcements from repo
Failed to fetch announcements due to "The SSL connection could not be established, see inner exception." (Attempted to fetch from https://raw.githubusercontent.com/LogicReinc/LogicReinc.BlendFarm/main/.data/announcements.json)

**Comment by LogicReinc** [comment]
From what I can see and guess, the exception is related to the SSL certificates or their validity.
This could be due to 2 reasons off the top of my head:
 - Your machine time is wrong, causing certificates to be considered invalid
 - Your machine is missing basic certificates somehow

The reason why this matters is because BlendFarm will try to download the blender version you're requesting, so if your certificates or machine time is out of whack, SSL will fail.

I hope this helps you on your way. I don't believe its a software issue.

(Note that I do not know Russian, so my answer is based on some Google Translate)

**Comment by kolotovalexander** [comment]
> From what I can see and guess, the exception is related to the SSL certificates or their validity. This could be due to 2 reasons off the top of my head:
> 
> * Your machine time is wrong, causing certificates to be considered invalid
> * Your machine is missing basic certificates somehow
> 
> The reason why this matters is because BlendFarm will try to download the blender version you're requesting, so if your certificates or machine time is out of whack, SSL will fail.
> 
I don't quite understand where to start solving this problem. Could you guide me? What do I need to do?
>
> I hope this helps you on your way. I don't believe its a software issue.
> 
I'm sorry I didn't translate the request into English myself. I am very sorry
> (Note that I do not know Russian, so my answer is based on some Google Translate)
