### ISSUE TITLE
Video textures not showing 

### ISSUE THREAD

**Issue by Emile2020** [LogicReinc/LogicReinc.BlendFarm#69]
When rendering a scene with a video texture, the surface becomes purple indicating that the file couldn't be found. Everything has been packed.

How to reproduce:
1. Create a scene with a surface
2. Set the texture of that surface to a image texture with as the image a video (.mp4)
3. Place a camera
4. Pack everything
5. Send it to the render app (as animation)

Example picture:
![1](https://user-images.githubusercontent.com/62842896/232037812-48e5c0ee-d992-451a-a2c5-4f5efa1e6a7f.png)
The purple should be a video

**Comment by Emile2020** [comment]
PS: When turning it into an image sequence, the frames rendered locally only show the images

**Comment by Emile2020** [comment]
After doing some research, it appears this is a blender issue, is there a workaround for this?

**Comment by hurricanz** [comment]
why ask him if there's a workaround for Blender's failures?
