### ISSUE TITLE
Save the state of System->Use Networked Path and the values for the OS paths as part of Image->Save Current Settings as Default

### ISSUE THREAD

**Issue by acollaborator** [LogicReinc/LogicReinc.BlendFarm#72]
Save the state of System->Use Networked Path and the values for the OS paths as part of Image->Save Current Settings as Default

**Comment by LogicReinc** [comment]
Agreed, though they should technically be a per-project setting.
At the moment all settings are global, so I'll probably have to introduce that at some point.

**Comment by LogicReinc** [comment]
Solved in upcoming 1.1.5.
(Saved on render)
