### ISSUE TITLE
question about an issue trying to locate version 3.6 of blender . thank you.

### ISSUE THREAD

**Issue by zeeyannosse** [LogicReinc/LogicReinc.BlendFarm#73]
![05072023_question_about_LOCAL_RENDER_FARM_ADDON](https://user-images.githubusercontent.com/115336559/236673476-21484d55-ab26-46a7-a20f-d26fda60afcb.jpg)

**Comment by LogicReinc** [comment]
@zeeyannosse If you look carefully, the expected directory name does not match, the name in the error says -windows64, while the one in your explorer does not. All the other tried names don't match it either.

So I assume that's where the issue is.
