### ISSUE TITLE
Not syncing large files

### ISSUE THREAD

**Issue by Avi3dcom** [LogicReinc/LogicReinc.BlendFarm#77]
Hi, i have an issue with syncing. It's seem to only sync small files.
When i try to render 1.6MB file it works perfectly and instantly, but when trying with a 2.4GB file (tried with two different large files) when clicking sync all nothing happened, also when clicking on render, there is the "Unsynced nodes" window pop-up and after clicking "Yes" the client has loading bar on bottom but the UI is still responding.
There are no msgs on both terminals. Last msg on client is: "Received prepareResp [44] from [::ffff:IP]:15000" and last msg on server is: "blender-3.5.1 already present. Also system monitor shows no heavy traffic, only about 77 bytes.
Issue on two different Windows client/master and one Linux servers. 
I'm ruining two Windows 11 client/master and one server POP_OS, I've tried Windows to Windows both sides acting as server and both as clients. I've tried Windows to Linux from both Windows machines as clients and Linux as server. None of my tests worked.

**Comment by LogicReinc** [comment]
I'm currently working on a way to not having to embed all files which should result in significantly smaller blend files.
But I'll also do a test to see what is going on with larger files.
I've mostly tested it with files up to about 300-500mb

**Comment by LogicReinc** [comment]
Sounds about right yea, was expecting something along those lines. Should be an easy fix. (And thus should be in upcoming build in 1-2 weeks hopefully.

**Comment by LogicReinc** [comment]
Solved in upcoming 1.1.5
