### ISSUE TITLE
Installing Blender Progres Bar

### ISSUE THREAD

**Issue by Tyguy047** [LogicReinc/LogicReinc.BlendFarm#78]
Not really a huge problem but I was wondering if you could add a progress bar or a way to tell if it is still installing Blender or if the software is frozen?
<img width="300" alt="Screenshot 2023-07-11 at 12 12 49 AM" src="https://github.com/LogicReinc/LogicReinc.BlendFarm/assets/115597578/a10fc04d-4df1-4e85-bb96-5afbbc5b63dd">

**P.S.: Tysm for making this I have been looking for something this easy to use for about a month! Literally one of the best software that exists! Thx for making it open-source and free!**

**Comment by LogicReinc** [comment]
Im writing it into the upcoming build (Which has been delayed for a while, but hoping to get it out this week)

**Comment by Tyguy047** [comment]
> Im writing it into the upcoming build (Which has been delayed for a while, but hoping to get it out this week)

Thanks! It's awesome when developers listen to their community! 10/10 software! 

Also is it possible to make this cross-platform? I like designing on my Mac and I was wondering if there's a way I can send the render job from my Mac instead of transferring the project to my PC and then rendering from my there?

**Comment by LogicReinc** [comment]
@Tyguy047 The software is already cross-platform, so I'm unsure what you mean?
Mac binaries are available in releases. Given they are x64 MacOS and not the new ARM-based macs, you should still be able to use them though, they just will not provide significant processing power for rendering. But for using other render nodes, it will work fine.

**Comment by Tyguy047** [comment]
So this means that if I am using an ARM Mac like my M1 MacBook Air I would not be able to send a job from this machine to my Windows PC? When I try to render now I get an error. I am not currently home so I don't remember the spefic error but I believe it was a GDI+ error? Not sure if that's even a real thing I haven't tried to render in a little while!

**Comment by LogicReinc** [comment]
I believe that should be the case yea. I know on MacOS you may have to install some packages. as written in the FAQ:
"You're running Linux or Mac but did not install libgdiplus and libc6-dev, install these and you should be good."

I know sometimes Mac gives an error, but it doesn't affect the render result.
I do not own a M1 macbook, only an older Macbook which I use for testing, so I can't really test it myself.

**Comment by atoav** [comment]
Just to chime in, I have been running 1.1.4 with the following devices in the "farm" successfully:

- Windows 10, 64 bit Laptop
- Laptop with Ubuntu 22.04 on it
- Macbook Pro M1

The M1 has been the slowest of the bunch (the other laptops have hefty RTX cards), but all worked fine.

**Comment by LogicReinc** [comment]
@atoav It makes sense that the M1 is kinda slow not only due to hardware, but also because it has to run Blender through translation layer (x86/x64 => ARM).

But yea, it should work, if you're merely using it as a client to send out requests it should be fine.

**Comment by LogicReinc** [comment]
Solved in upcoming 1.1.5
