### ISSUE TITLE
App UI too large for my screen

### ISSUE THREAD

**Issue by enbyautumn** [LogicReinc/LogicReinc.BlendFarm#9]
I am on windows 10 with a 1920x1080 display set to 125% scaling.  After opening a project, the button to start the render is off-screen and I am unable to press it. 

![image](https://user-images.githubusercontent.com/60362123/120806466-e3650b80-c514-11eb-9e21-1cbb4409e2ea.png)

A temporary solution is enabling live render, as that button is high enough up on screen for it to be pressed.
One of the advanced DPI scaling compatibility options might also allow the button to be pressed when the taskbar is set to hide automatically.

**Comment by LogicReinc** [comment]
The application was designed with a minimum height of 950px in mind. So yea.. 
I'll see if I can implement a scroll bar in there for very small screens.

**Comment by LogicReinc** [comment]
Sorry for the late update. Was busy with other work.
1.0.6 is updated with a minimum height of 500px (excl scaling), it does this by making the right panel scrollable.
This should allow you to use it without issues on your screen with scaling.
